# Site settings
title: Shape Shapes
email: khoon@khoonster.com
description: Shape Shapes is an exhibition platform for artist's shapes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.shapeshapes.com"

# Build settings
markdown: kramdown
exclude:
  - bin
  - bower_components
  - bower.json
  - CNAME
  - Gemfile*
  - gulpfile.js
  - LICENSE
  - package.json
  - README*
