# Site settings
title: Shape Shapes
email: khoon@khoonster.com
description: > # this means to ignore newlines until "baseurl:"
  A little site for now...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.shapeshapes.com"

# Build settings
markdown: kramdown
exclude:
  - bower_components
  - bower.json
  - Gemfile*
  - LICENSE
  - README*
  - gulpfile.js
  - package.json
