# Site settings
title: Khoon Choi
email: khoon@khoonster.com
description: > # this means to ignore newlines until "baseurl:"
  A little site for now...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://khoonster.github.io"

# Build settings
markdown: kramdown
exclude:
  - bower_components
  - bower.json
  - Gemfile*
  - LICENSE
  - README*
